#!/usr/bin/env bash
set -euo pipefail

case ${BASH_SOURCE[0]} in
    */*) script_dir=${BASH_SOURCE[0]%/*} ;;
    *) script_dir=. ;;
esac
repo_root=$(cd -P -- "$script_dir" && pwd)

if [[ $PWD != "$repo_root" ]]; then
    printf 'ERROR: run start.sh from the repository root: %s\n' "$repo_root" >&2
    exit 1
fi

export PATH="$HOME/.local/bin:$PATH"
config_file=${AGENT_WORKFLOW_MANAGER_CONFIG_FILE:-$repo_root/config.sh}
sample_config_file="$repo_root/sample_config.sh"
host_override_set=${AGENT_WORKFLOW_MANAGER_HOST+x}
host_override=${AGENT_WORKFLOW_MANAGER_HOST-}
port_override_set=${AGENT_WORKFLOW_MANAGER_PORT+x}
port_override=${AGENT_WORKFLOW_MANAGER_PORT-}
notifications_override_set=${AGENT_WORKFLOW_MANAGER_NOTIFICATIONS+x}
notifications_override=${AGENT_WORKFLOW_MANAGER_NOTIFICATIONS-}
notify_config_override_set=${NOTIFY_CONFIG+x}
notify_config_override=${NOTIFY_CONFIG-}
runtime_config_temp=""

require_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        printf 'ERROR: required command not found: %s\n' "$1" >&2
        exit 1
    fi
}

validate_ipv4() {
    local value=$1
    local octets
    local octet

    if [[ ! $value =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        return 1
    fi
    IFS=. read -r -a octets <<<"$value"
    for octet in "${octets[@]}"; do
        if [[ $octet != 0 && $octet == 0* ]] || ((10#$octet > 255)); then
            return 1
        fi
    done
}

validate_port() {
    local value=$1
    [[ $value =~ ^[0-9]{1,5}$ ]] &&
        ((10#$value >= 1 && 10#$value <= 65535))
}

prompt_yes_by_default() {
    local prompt=$1
    local answer

    printf '%s [Y/n] ' "$prompt" >&2
    if ! IFS= read -r answer; then
        return 2
    fi
    [[ -z $answer || $answer == y || $answer == Y || $answer == yes || $answer == YES ]]
}

detect_tailscale_ipv4() {
    local output
    local candidate
    local detected=""
    local count=0

    command -v tailscale >/dev/null 2>&1 || return 1
    output=$(tailscale ip -4 2>/dev/null) || return 1
    while IFS= read -r candidate; do
        if validate_ipv4 "$candidate" && [[ $candidate != 0.0.0.0 ]]; then
            detected=$candidate
            ((count += 1))
        fi
    done <<<"$output"
    [[ $count == 1 ]] || return 1
    printf '%s' "$detected"
}

write_runtime_config() {
    runtime_config_temp=$(mktemp "${config_file}.tmp.XXXXXX")
    {
        printf '# Generated by bash start.sh. Edit values here, then rerun bash start.sh.\n'
        printf '# Notification credentials belong only in NOTIFY_CONFIG, never in this file.\n'
        printf 'AGENT_WORKFLOW_MANAGER_HOST=%q\n' "$AGENT_WORKFLOW_MANAGER_HOST"
        printf 'AGENT_WORKFLOW_MANAGER_PORT=%q\n' "$AGENT_WORKFLOW_MANAGER_PORT"
        printf 'AGENT_WORKFLOW_MANAGER_NOTIFICATIONS=%q\n' \
            "$AGENT_WORKFLOW_MANAGER_NOTIFICATIONS"
        printf 'NOTIFY_CONFIG=%q\n' "$NOTIFY_CONFIG"
    } >"$runtime_config_temp"
    chmod 600 "$runtime_config_temp"
    mv -- "$runtime_config_temp" "$config_file"
    runtime_config_temp=""
}

run_first_time_setup() {
    local detected_ip
    local answer_status
    local entered_ip

    if detected_ip=$(detect_tailscale_ipv4); then
        printf 'Tailscale IPv4 %s was detected.\n' "$detected_ip" >&2
        if prompt_yes_by_default \
            'Use it so the Runner UI can be accessed from other tailnet devices?'; then
            AGENT_WORKFLOW_MANAGER_HOST=$detected_ip
        else
            AGENT_WORKFLOW_MANAGER_HOST=127.0.0.1
        fi
    else
        printf 'Tailscale IPv4 could not be detected.\n' >&2
        if prompt_yes_by_default 'Start in local-only mode on 127.0.0.1?'; then
            AGENT_WORKFLOW_MANAGER_HOST=127.0.0.1
        else
            answer_status=$?
            if [[ $answer_status == 2 ]]; then
                AGENT_WORKFLOW_MANAGER_HOST=127.0.0.1
            else
                while true; do
                    printf 'Explicit trusted interface IPv4 address: ' >&2
                    if ! IFS= read -r entered_ip; then
                        printf '\nERROR: setup input ended before an IPv4 address was entered.\n' >&2
                        exit 2
                    fi
                    if validate_ipv4 "$entered_ip" && [[ $entered_ip != 0.0.0.0 ]]; then
                        AGENT_WORKFLOW_MANAGER_HOST=$entered_ip
                        break
                    fi
                    printf 'Invalid IPv4 address; enter one interface address, not 0.0.0.0.\n' >&2
                done
            fi
        fi
    fi

    write_runtime_config
    printf 'Saved runtime configuration to %s\n' "$config_file"
}

AGENT_WORKFLOW_MANAGER_HOST=127.0.0.1
AGENT_WORKFLOW_MANAGER_PORT=8765
AGENT_WORKFLOW_MANAGER_NOTIFICATIONS=auto
NOTIFY_CONFIG="$HOME/.config/notify/config"

first_run=false
if [[ ! -f $config_file ]]; then
    cp -- "$sample_config_file" "$config_file"
    chmod 600 "$config_file"
    first_run=true

    cleanup_incomplete_setup() {
        if [[ -n $runtime_config_temp ]]; then
            rm -f -- "$runtime_config_temp"
        fi
        if [[ $first_run == true ]]; then
            rm -f -- "$config_file"
        fi
    }
    trap cleanup_incomplete_setup EXIT
fi

# shellcheck disable=SC1090
if ! source "$config_file"; then
    printf 'ERROR: failed to load runtime configuration: %s\n' "$config_file" >&2
    exit 2
fi

if [[ $first_run == true ]]; then
    run_first_time_setup
    first_run=false
    trap - EXIT
fi

if [[ $host_override_set ]]; then
    AGENT_WORKFLOW_MANAGER_HOST=$host_override
fi
if [[ $port_override_set ]]; then
    AGENT_WORKFLOW_MANAGER_PORT=$port_override
fi
if [[ $notifications_override_set ]]; then
    AGENT_WORKFLOW_MANAGER_NOTIFICATIONS=$notifications_override
fi
if [[ $notify_config_override_set ]]; then
    NOTIFY_CONFIG=$notify_config_override
fi

if ! validate_ipv4 "${AGENT_WORKFLOW_MANAGER_HOST-}"; then
    printf 'ERROR: AGENT_WORKFLOW_MANAGER_HOST must be an explicit IPv4 address.\n' >&2
    exit 2
fi
if [[ $AGENT_WORKFLOW_MANAGER_HOST == 0.0.0.0 ]]; then
    printf '%s\n' \
        'ERROR: refusing wildcard bind 0.0.0.0; choose one trusted interface IPv4 address.' >&2
    exit 2
fi
if ! validate_port "${AGENT_WORKFLOW_MANAGER_PORT-}"; then
    printf 'ERROR: AGENT_WORKFLOW_MANAGER_PORT must be an integer from 1 to 65535.\n' >&2
    exit 2
fi
case ${AGENT_WORKFLOW_MANAGER_NOTIFICATIONS-} in
    auto | enabled | disabled) ;;
    *)
        printf '%s\n' \
            'ERROR: AGENT_WORKFLOW_MANAGER_NOTIFICATIONS must be auto, enabled, or disabled.' >&2
        exit 2
        ;;
esac
if [[ -z ${NOTIFY_CONFIG-} ]]; then
    printf 'ERROR: NOTIFY_CONFIG must not be empty.\n' >&2
    exit 2
fi
export NOTIFY_CONFIG

require_command uv
printf 'Syncing Python dependencies...\n'
uv sync --locked
require_command purplemux

notification_mode=$AGENT_WORKFLOW_MANAGER_NOTIFICATIONS
if [[ $notification_mode != disabled ]]; then
    if ! command -v notify >/dev/null 2>&1; then
        require_command curl
        install_root=$(mktemp -d)
        cleanup_install() { rm -rf -- "$install_root"; }
        trap cleanup_install EXIT
        printf 'Installing the public notify CLI...\n'
        mkdir -p "$install_root/notify-server/bin"
        curl --fail --silent --show-error --location \
            --output "$install_root/notify-server/install-cli.sh" \
            https://raw.githubusercontent.com/eletim/notify-server/main/install-cli.sh
        curl --fail --silent --show-error --location \
            --output "$install_root/notify-server/bin/notify" \
            https://raw.githubusercontent.com/eletim/notify-server/main/bin/notify
        bash "$install_root/notify-server/install-cli.sh"
        trap - EXIT
        cleanup_install
    fi

    notify_config_dir=${NOTIFY_CONFIG%/*}
    if [[ $notify_config_dir == "$NOTIFY_CONFIG" ]]; then
        notify_config_dir=.
    fi
    mkdir -p -- "$notify_config_dir"
    if [[ ! -f $NOTIFY_CONFIG ]]; then
        {
            printf 'NOTIFY_SERVER=https://eletim.jp\n'
            printf 'NOTIFY_TOPIC=agents\n'
            printf '# NOTIFY_TOKEN=tk_...\n'
        } >"$NOTIFY_CONFIG"
        chmod 600 "$NOTIFY_CONFIG"
        printf 'Created notify configuration: %s\n' "$NOTIFY_CONFIG"
    fi

    token_configured=false
    if [[ -n ${NOTIFY_TOKEN:-} ]]; then
        token_configured=true
    elif (
        set +u
        # shellcheck disable=SC1090
        source "$NOTIFY_CONFIG" >/dev/null 2>&1
        [[ -n ${NOTIFY_TOKEN:-} ]]
    ); then
        token_configured=true
    fi

    if [[ $token_configured == false && -t 0 ]]; then
        printf 'Notify token (leave blank to disable notifications): ' >&2
        IFS= read -r -s notify_token
        printf '\n' >&2
        if [[ -n $notify_token ]]; then
            printf 'NOTIFY_TOKEN=%q\n' "$notify_token" >>"$NOTIFY_CONFIG"
            chmod 600 "$NOTIFY_CONFIG"
            unset notify_token
            token_configured=true
            printf 'Notify token saved to %s\n' "$NOTIFY_CONFIG"
        fi
    fi

    if [[ $token_configured == true ]]; then
        export AGENT_WORKFLOW_MANAGER_NOTIFICATIONS=1
        printf 'Terminal notifications enabled.\n'
    elif [[ $notification_mode == enabled ]]; then
        export AGENT_WORKFLOW_MANAGER_NOTIFICATIONS=0
        printf 'Terminal notifications requested but no token is configured; continuing disabled.\n'
    else
        export AGENT_WORKFLOW_MANAGER_NOTIFICATIONS=0
        printf 'Terminal notifications disabled; Runner startup will continue.\n'
    fi
else
    export AGENT_WORKFLOW_MANAGER_NOTIFICATIONS=0
    printf 'Terminal notifications disabled by runtime configuration.\n'
fi

if [[ $AGENT_WORKFLOW_MANAGER_HOST != 127.0.0.1 ]]; then
    printf '%s\n' \
        'WARNING: this UI executes arbitrary trusted Python; never expose this address publicly.'
fi
printf '\nAgent Workflow Manager:\n'
printf 'http://%s:%s\n' "$AGENT_WORKFLOW_MANAGER_HOST" "$AGENT_WORKFLOW_MANAGER_PORT"
printf 'Notifications: %s\n' \
    "$([[ $AGENT_WORKFLOW_MANAGER_NOTIFICATIONS == 1 ]] && printf enabled || printf disabled)"
printf 'Notify config: %s\n' "$NOTIFY_CONFIG"

exec uv run python -m purplemux_client.web \
    --host "$AGENT_WORKFLOW_MANAGER_HOST" \
    --port "$AGENT_WORKFLOW_MANAGER_PORT"
