#!/usr/bin/env bash

set -euo pipefail

case ${BASH_SOURCE[0]} in
    */*) script_dir=${BASH_SOURCE[0]%/*} ;;
    *) script_dir=. ;;
esac
REPO_ROOT=$(cd -P -- "$script_dir" && pwd)
CONFIG_FILE="$REPO_ROOT/config.sh"

# Keep the caller's PATH and add the conventional user-local CLI directory.
export PATH="$HOME/.local/bin:$PATH"

AGENT_WORKFLOW_MANAGER_HOST=""
AGENT_WORKFLOW_MANAGER_PORT=""
AGENT_WORKFLOW_MANAGER_PATH=""

if [[ -f $CONFIG_FILE ]]; then
    if ! source "$CONFIG_FILE"; then
        printf 'ERROR: failed to load %s.\n' "$CONFIG_FILE" >&2
        printf 'Fix the shell syntax in config.sh, then retry: ./start.sh\n' >&2
        exit 1
    fi
fi

config_changed=false

prompt_if_empty() {
    local variable_name=$1
    local prompt=$2
    local default_value=$3
    local current_value=${!variable_name}
    local entered_value

    if [[ -n $current_value ]]; then
        return
    fi
    printf '%s [%s]: ' "$prompt" "$default_value" >&2
    if ! IFS= read -r entered_value; then
        printf '\nERROR: configuration input ended before %s was set.\n' "$variable_name" >&2
        exit 1
    fi
    printf -v "$variable_name" '%s' "${entered_value:-$default_value}"
    config_changed=true
}

prompt_if_empty AGENT_WORKFLOW_MANAGER_HOST "Bind host" "127.0.0.1"
prompt_if_empty AGENT_WORKFLOW_MANAGER_PORT "Port" "8765"

if [[ ! $AGENT_WORKFLOW_MANAGER_PORT =~ ^[0-9]+$ ]] ||
    ((10#$AGENT_WORKFLOW_MANAGER_PORT < 1 || 10#$AGENT_WORKFLOW_MANAGER_PORT > 65535)); then
    printf 'ERROR: AGENT_WORKFLOW_MANAGER_PORT must be an integer from 1 to 65535 (got %q).\n' \
        "$AGENT_WORKFLOW_MANAGER_PORT" >&2
    exit 1
fi

if [[ $config_changed == true || ! -f $CONFIG_FILE ]]; then
    {
        printf '# Generated by ./start.sh. Edit these values, then rerun ./start.sh.\n'
        printf 'AGENT_WORKFLOW_MANAGER_HOST=%q\n' "$AGENT_WORKFLOW_MANAGER_HOST"
        printf 'AGENT_WORKFLOW_MANAGER_PORT=%q\n' "$AGENT_WORKFLOW_MANAGER_PORT"
        printf 'AGENT_WORKFLOW_MANAGER_PATH=%q\n' "$AGENT_WORKFLOW_MANAGER_PATH"
    } >"$CONFIG_FILE"
    printf 'Saved configuration to %s\n' "$CONFIG_FILE"
fi

if [[ -n $AGENT_WORKFLOW_MANAGER_PATH ]]; then
    export PATH="$AGENT_WORKFLOW_MANAGER_PATH:$PATH"
fi

missing_dependency=false

if ! command -v purplemux >/dev/null 2>&1; then
    missing_dependency=true
    cat >&2 <<'EOF'

ERROR: purplemux command was not found.

agent-workflow-manager workflows use the PurpleMux CLI to create workspaces
and communicate with Codex, Claude, and Shell tabs.

First verify whether you already have a PurpleMux checkout. From the PurpleMux
repository root, run:

  node bin/cli.js --help

If that works, expose the CLI on PATH. For example, create your own wrapper:

  mkdir -p ~/.local/bin
  cat > ~/.local/bin/purplemux <<'WRAPPER'
  #!/usr/bin/env bash
  exec node "/absolute/path/to/purplemux/bin/cli.js" "$@"
  WRAPPER
  chmod +x ~/.local/bin/purplemux

Then ensure the directory is on PATH (start.sh also adds this directory):

  export PATH="$HOME/.local/bin:$PATH"

Verify the completed setup:

  command -v purplemux
  purplemux --help

If PurpleMux is not installed, install or clone it separately, complete its
normal dependency/setup procedure, and verify `node bin/cli.js --help` before
exposing the CLI on PATH. start.sh does not clone, install, or create wrappers.
EOF
fi

if ! command -v gh >/dev/null 2>&1; then
    missing_dependency=true
    cat >&2 <<'EOF'

ERROR: GitHub CLI (gh) was not found.

Workflows use GitHub CLI for pull-request and issue operations. Install `gh`
separately using GitHub's official instructions or your OS package manager;
start.sh does not install it or modify your shell profile.

After installation, authenticate if needed and verify both discovery and
authentication:

  command -v gh
  gh --version
  gh auth status
EOF
fi

if ! command -v uv >/dev/null 2>&1; then
    missing_dependency=true
    cat >&2 <<'EOF'

ERROR: uv was not found.

uv is required to create the project Python environment and launch the Runner
with its locked dependencies. Install uv separately using the official uv
installation instructions or an appropriate package manager. start.sh never
installs Python tools or packages automatically.

Ensure uv's installation directory is on PATH, then verify:

  command -v uv
  uv --version
EOF
fi

if [[ $missing_dependency == true ]]; then
    cat >&2 <<'EOF'

Review your PATH with:

  printf '%s\n' "$PATH"

After fixing every dependency above, verify each command and retry:

  command -v purplemux
  command -v gh
  command -v uv
  ./start.sh
EOF
    exit 1
fi

printf 'Starting Agent Workflow Manager\n'
printf 'Bind: %s:%s\n' "$AGENT_WORKFLOW_MANAGER_HOST" "$AGENT_WORKFLOW_MANAGER_PORT"
printf 'URL:  http://%s:%s\n' "$AGENT_WORKFLOW_MANAGER_HOST" "$AGENT_WORKFLOW_MANAGER_PORT"

cd "$REPO_ROOT"
exec uv run python -m purplemux_client.web \
    --host "$AGENT_WORKFLOW_MANAGER_HOST" \
    --port "$AGENT_WORKFLOW_MANAGER_PORT"
